# Generated by Django 3.0.8 on 2020-07-30 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_userregister'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRegister',
        ),
    ]
