# Generated by Django 3.0.8 on 2020-08-05 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_delete_userregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='favorite',
            field=models.BooleanField(default=False, verbose_name=False),
            preserve_default=False,
        ),
    ]
